apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      initContainers:           # Waits for config-server before starting
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://config-server:8888/actuator/health; do echo waiting; sleep 5; done']
      containers:
        - name: discovery-server
          image: "{{ .Values.imageRegistry }}/spring-petclinic-discovery-server:{{ .Values.imageTag }}"
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            limits:
              memory: "{{ .Values.services.discoveryServer.memory }}"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: petclinic
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761
